In [ ]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path().resolve().parent

csv_2020 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2020.csv'
csv_2021 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2021.csv'
csv_2022 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2022.csv'
csv_2023 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2023.csv'
csv_2024 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2024.csv'
csv_2025 = BASE_DIR / 'extract' / 'raw' / 'data_vf' /  'data_2025.csv'

csv_cities = BASE_DIR / 'extract' / 'raw' / 'datagouv_commun.csv'

csv_pop22 = BASE_DIR / 'extract' / 'raw' / 'population' /  'population-2022.csv'
csv_pop23 = BASE_DIR / 'extract' / 'raw' / 'population' /  'population-2023.csv'
csv_pop24 = BASE_DIR / 'extract' / 'raw' / 'population' /  'population-2024.csv'
csv_pop25 = BASE_DIR / 'extract' / 'raw' / 'population' /  'population-2025.csv'

In [ ]:
# Création des DataFrames
df_2020 = pd.read_csv(csv_2020)
df_2021 = pd.read_csv(csv_2021)
df_2022 = pd.read_csv(csv_2022)
df_2023 = pd.read_csv(csv_2023)
df_2024 = pd.read_csv(csv_2024)
df_2024 = pd.read_csv(csv_2025)


df_pop20 = pd.read_csv(csv_2025)

CITIES_DATAFRAME = pd.read_csv(csv_cities)

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_5324\217291187.py:2: DtypeWarning: Columns (11,13,18,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv(csv_2020)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_5324\217291187.py:3: DtypeWarning: Columns (19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv(csv_2021)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_5324\217291187.py:5: DtypeWarning: Columns (19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(csv_2023)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_5324\217291187.py:8: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  CITIES_DATAFRAME = pd.read_csv(csv_cities)

In [109]:
CITIES_DATAFRAME = CITIES_DATAFRAME.drop(CITIES_DATAFRAME.columns[[0,4,5,8,9,10,11,14,15,16,17,18,19,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46]], axis=1)

In [110]:
df = pd.concat([df_2020, df_2021, df_2022, df_2023, df_2024], ignore_index=True)

In [111]:
df = df.merge(CITIES_DATAFRAME, how="left", on="code_postal")

In [112]:
df.head()

,__id,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,...,longitude,latitude,code_insee,nom_standard,nom_sans_pronom,nom_sans_accent,nom_standard_majuscule,dep_code,dep_nom,codes_postaux
0,37,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,...,5.251962,46.212201,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100..."
1,37,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,...,5.251962,46.212201,01344,Saint-Denis-lès-Bourg,Saint-Denis-lès-Bourg,saint-denis-les-bourg,SAINT-DENIS-LÈS-BOURG,01,Ain,"01012, 01006, 01000"
2,43,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,5.217651,46.208039,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100..."
3,43,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,5.217651,46.208039,01344,Saint-Denis-lès-Bourg,Saint-Denis-lès-Bourg,saint-denis-les-bourg,SAINT-DENIS-LÈS-BOURG,01,Ain,"01012, 01006, 01000"
4,44,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,5.217651,46.208039,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100..."

In [113]:
df.shape

(685998, 49)

In [114]:
df['date_mutation'] = pd.to_datetime(df['date_mutation'])

annual_cp = df.groupby([df['code_postal'], df['date_mutation'].dt.to_period('Y')]).agg({
    'valeur_fonciere': 'mean'
}).sort_index()

annual_cp['variation'] = annual_cp.groupby(level=0)['valeur_fonciere'].diff()

def trend(x):
    if x > 0:
        return 'hausse'
    if x < 0:
        return 'baisse'
    return 'stable'

annual_cp['tendance'] = annual_cp['variation'].fillna(0).apply(trend)

df['année'] = df['date_mutation'].dt.year
df['y'] = df.apply(lambda row: 
                   annual_cp.loc[(row['code_postal'], pd.Period(row['date_mutation'], freq='Y')), 'tendance'], 
                   axis=1)

df.head()

,__id,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,...,code_insee,nom_standard,nom_sans_pronom,nom_sans_accent,nom_standard_majuscule,dep_code,dep_nom,codes_postaux,année,y
0,37,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,...,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100...",2020,stable
1,37,2020-11,2020-07-03,1,Vente,169111.0,71.0,NaN,RUE BRICHEMER,0605,...,01344,Saint-Denis-lès-Bourg,Saint-Denis-lès-Bourg,saint-denis-les-bourg,SAINT-DENIS-LÈS-BOURG,01,Ain,"01012, 01006, 01000",2020,stable
2,43,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100...",2020,stable
3,43,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,01344,Saint-Denis-lès-Bourg,Saint-Denis-lès-Bourg,saint-denis-les-bourg,SAINT-DENIS-LÈS-BOURG,01,Ain,"01012, 01006, 01000",2020,stable
4,44,2020-14,2020-07-02,1,Vente en l'état futur d'achèvement,360000.0,12.0,NaN,RUE DU 23EME R.I.,3740,...,01053,Bourg-en-Bresse,Bourg-en-Bresse,bourg-en-bresse,BOURG-EN-BRESSE,01,Ain,"01003, 01007, 01060, 01013, 01006, 01005, 0100...",2020,stable

In [63]:
print(df['y'].value_counts())

y
hausse    600
stable    200
baisse    200
Name: count, dtype: int64

In [65]:
print(df['code_postal'].value_counts())

code_postal
1000    1000
Name: count, dtype: int64

In [64]:
df.columns

Index(['__id', 'id_mutation', 'date_mutation', 'numero_disposition',
       'nature_mutation', 'valeur_fonciere', 'adresse_numero',
       'adresse_suffixe', 'adresse_nom_voie', 'adresse_code_voie',
       'code_postal', 'code_commune', 'nom_commune', 'code_departement',
       'ancien_code_commune', 'ancien_nom_commune', 'id_parcelle',
       'ancien_id_parcelle', 'numero_volume', 'lot1_numero',
       'lot1_surface_carrez', 'lot2_numero', 'lot2_surface_carrez',
       'lot3_numero', 'lot3_surface_carrez', 'lot4_numero',
       'lot4_surface_carrez', 'lot5_numero', 'lot5_surface_carrez',
       'nombre_lots', 'code_type_local', 'type_local', 'surface_reelle_bati',
       'nombre_pieces_principales', 'code_nature_culture', 'nature_culture',
       'code_nature_culture_speciale', 'nature_culture_speciale',
       'surface_terrain', 'longitude', 'latitude', 'code_insee',
       'nom_standard', 'nom_sans_pronom', 'nom_sans_accent',
       'nom_standard_majuscule', 'dep_code', 'dep_nom', 'codes_postaux', 'y',
       'année'],
      dtype='object')

In [78]:
cols_keep= [
    'code_postal', 'code_commune', 'nom_commune', 'code_departement',
    'ancien_code_commune', 'ancien_nom_commune', 'dep_code', 'dep_nom', 'codes_postaux'
]

In [ ]:
df['date_mutation'] = pd.to_datetime(df['date_mutation'])
df['annee'] = df['date_mutation'].dt.year

cols_ville = [
    'code_commune', 'nom_commune', 'code_departement',
    'ancien_code_commune', 'ancien_nom_commune', 'dep_code', 'dep_nom'
]

vf_annee = df.groupby(['annee', 'code_postal']).agg(
    valeur_fonciere=('valeur_fonciere', 'mean')
)

vf_annee['variation'] = vf_annee.groupby('code_postal')['valeur_fonciere'].diff()

def market_trend(x):
    if x > 0:
        return 'hausse'
    elif x < 0:
        return 'baisse'
    else:
        return 'stable'

vf_annee['y'] = vf_annee['variation'].apply(market_trend)

ville_info = df.groupby(['annee', 'code_postal'])[cols_ville].first()

df_final = vf_annee.merge(ville_info, left_index=True, right_index=True).reset_index()

   annee  code_postal  valeur_fonciere   variation       y  code_commune  \
0   2020         1000      155054.6590         NaN  stable          1053
1   2021         1000      158685.1000   3630.4410  hausse          1344
2   2022         1000      171679.2600  12994.1600  hausse          1053
3   2023         1000      257934.0194  86254.7594  hausse          1053
4   2024         1000      191355.0680 -66578.9514  baisse          1053

             nom_commune  code_departement  ancien_code_commune  \
0        Bourg-en-Bresse                 1                  NaN
1  Saint-Denis-lès-Bourg                 1                  NaN
2        Bourg-en-Bresse                 1                  NaN
3        Bourg-en-Bresse                 1                  NaN
4        Bourg-en-Bresse                 1                  NaN

   ancien_nom_commune dep_code dep_nom
0                 NaN       01     Ain
1                 NaN       01     Ain
2                 NaN       01     Ain
3                 NaN       01     Ain
4                 NaN       01     Ain

In [99]:
print(df_final.head(100))

   annee  code_postal  valeur_fonciere   variation       y  code_commune  \
0   2020         1000      155054.6590         NaN  stable          1053
1   2021         1000      158685.1000   3630.4410  hausse          1344
2   2022         1000      171679.2600  12994.1600  hausse          1053
3   2023         1000      257934.0194  86254.7594  hausse          1053
4   2024         1000      191355.0680 -66578.9514  baisse          1053

             nom_commune  code_departement  ancien_code_commune  \
0        Bourg-en-Bresse                 1                  NaN
1  Saint-Denis-lès-Bourg                 1                  NaN
2        Bourg-en-Bresse                 1                  NaN
3        Bourg-en-Bresse                 1                  NaN
4        Bourg-en-Bresse                 1                  NaN

   ancien_nom_commune dep_code dep_nom
0                 NaN       01     Ain
1                 NaN       01     Ain
2                 NaN       01     Ain
3                 NaN       01     Ain
4                 NaN       01     Ain

In [115]:
df['code_postal'].unique()

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000, 11000, 12000, 14000, 15000, 16000, 17000, 18000, 19000,
       21000, 22000, 23000, 24000, 25000, 26000, 27000, 28000, 29000,
       20000, 30000])