In [ ]:
import pandas as pd
from pathlib import Path
import numpy as np
import os

BASE_DIR = Path().resolve().parents[2]

csv_2020 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2020.csv'
csv_2021 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2021.csv'
csv_2022 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2022.csv'
csv_2023 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2023.csv'
csv_2024 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2024.csv'
csv_2025 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2025.csv'

csv_communes_2022 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2022.csv'
csv_communes_2023 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2023.csv'
csv_communes_2024 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2024.csv'
csv_communes_2025 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2025.csv'

csv_taxe_fonciere = BASE_DIR / 'flatfiles' / 'taxe_fonciere_chefs_lieux_2021_2024.csv'

taux_inflation = BASE_DIR / 'flatfiles' / 'taux_inflation.csv'

nbr_emploi_par_region = BASE_DIR / 'flatfiles' / 'nbr_emploi_par_region.csv'

In [2]:
# Création des DataFrames
df_2020 = pd.read_csv(csv_2020)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\2454854937.py:2: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv(csv_2020)

In [11]:
df_2021 = pd.read_csv(csv_2021)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\4291009226.py:1: DtypeWarning: Columns (10,12,14,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv(csv_2021)

In [13]:
df_2022 = pd.read_csv(csv_2022)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\66118111.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv(csv_2022)

In [15]:
df_2023 = pd.read_csv(csv_2023)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\2045294576.py:1: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,26,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(csv_2023)

In [4]:
df_2024 = pd.read_csv(csv_2024)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\401764953.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv(csv_2024)

In [8]:
df_2025 = pd.read_csv(csv_2025)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\1456618700.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(csv_2025)

In [ ]:
cols = [
    'date_mutation',
    'valeur_fonciere',
    'surface_reelle_bati',
    'code_commune',
    'type_local',
    'nombre_pieces_principales',
    'longitude',
    'latitude',
    'code_postal',
    'id_mutation'
]

def prepare_and_agg(df):

    os.makedirs('raw', exist_ok=True)
    
    df = df[cols].copy()
    df['prix_m2'] = df['valeur_fonciere'] / df['surface_reelle_bati']
    df['annee'] = pd.to_datetime(df['date_mutation']).dt.year
    
    df_agg = df.groupby(['code_commune', 'annee']).agg({
        'prix_m2': 'mean',
        'surface_reelle_bati': 'mean',
        'id_mutation': 'count'
    }).rename(columns={'id_mutation':'nb_ventes'}).reset_index()
    
    annee= df['annee'].unique()[0] 
    output_path = os.path.join('raw', f'csv_agg_{annee}.csv')
    
    df_agg.to_csv(output_path, index=False, sep=';', encoding='utf-8')
    
    print(f"Fichier CSV enregistré ici : {output_path}")
    return df_agg

In [9]:
df_agg_2020 = prepare_and_agg(df_2020)

Fichier CSV enregistré ici : raw\csv_agg_2020.csv

In [12]:
df_agg_2021 = prepare_and_agg(df_2021)

Fichier CSV enregistré ici : raw\csv_agg_2021.csv

In [14]:
df_agg_2022 = prepare_and_agg(df_2022)

Fichier CSV enregistré ici : raw\csv_agg_2022.csv

In [16]:
df_agg_2023 = prepare_and_agg(df_2023)

Fichier CSV enregistré ici : raw\csv_agg_2023.csv

In [7]:
df_agg_2024 = prepare_and_agg(df_2024)

Fichier CSV enregistré ici : raw\csv_agg_2024.csv

In [9]:
df_agg_2025 = prepare_and_agg(df_2025)

Fichier CSV enregistré ici : raw\csv_agg_2025.csv

In [510]:
df_agg_2020 = pd.read_csv(r'raw\csv_agg_2020.csv', sep=';')
df_agg_2021 = pd.read_csv(r'raw\csv_agg_2021.csv', sep=';')
df_agg_2022 = pd.read_csv(r'raw\csv_agg_2022.csv', sep=';')
df_agg_2023 = pd.read_csv(r'raw\csv_agg_2023.csv', sep=';')
df_agg_2024 = pd.read_csv(r'raw\csv_agg_2024.csv', sep=';')
df_agg_2025 = pd.read_csv(r'raw\csv_agg_2025.csv', sep=';')

# Concaténer tous les DataFrames
df_agg_all = pd.concat([df_agg_2020, df_agg_2021, df_agg_2022, df_agg_2023, df_agg_2024,df_agg_2025
], ignore_index=True)

In [513]:
df_agg_all.head()

  code_commune  annee      prix_m2  surface_reelle_bati  nb_ventes
0         1001   2020  1508.351938           132.857143         15
1         1002   2020  2022.908835            47.000000         10
2         1004   2020  2530.613622            91.926136        433
3         1005   2020  3277.989223           105.478261         57
4         1006   2020  2326.979167           110.000000         12

In [514]:
output_path = os.path.join('raw', f'csv_agg_all.csv')
df_agg_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [515]:
df_communes_2022 = pd.read_csv(csv_communes_2022)
df_communes_2023 = pd.read_csv(csv_communes_2023)
df_communes_2024 = pd.read_csv(csv_communes_2024)
df_communes_2025 = pd.read_csv(csv_communes_2025)
df_communes_2020 = df_communes_2022.copy()
df_communes_2021 = df_communes_2022.copy()

df_communes_2020['annee'] = 2020
df_communes_2021['annee'] = 2021
df_communes_2022['annee'] = 2022
df_communes_2023['annee'] = 2023
df_communes_2024['annee'] = 2024
df_communes_2025['annee'] = 2025

df_communes_all = pd.concat([
    df_communes_2020, df_communes_2021,df_communes_2022, df_communes_2023, df_communes_2024,df_communes_2025
], ignore_index=True)

output_path = os.path.join('raw', f'csv_communes_all.csv')
df_communes_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_16100\113993347.py:1: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2022 = pd.read_csv(csv_communes_2022)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_16100\113993347.py:2: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2023 = pd.read_csv(csv_communes_2023)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_16100\113993347.py:3: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2024 = pd.read_csv(csv_communes_2024)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_16100\113993347.py:4: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi, 5: code_unite_urbaine) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2025 = pd.read_csv(csv_communes_2025)

In [516]:
df_communes_all.columns

Index(['Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve', 'annee', 'code_unite_urbaine',
       'nom_unite_urbaine', 'taille_unite_urbaine',
       'type_commune_unite_urbaine', 'statut_commune_unite_urbaine',
       'grille_densite_texte', 'niveau_equipements_services',
       'niveau_equipements_services_texte'],
      dtype='str')

In [517]:
cols_commune = [
    'annee','code_insee', 'nom_standard', 'code_postal',
    'dep_code', 'dep_nom', 'reg_code', 'reg_nom',
    'population', 'densite', 'superficie_km2',
    'latitude_centre', 'longitude_centre','zone_emploi'
]
df_comm = df_communes_all[cols_commune]


df_comm[df_comm['annee'] == 2020].head(10)

,annee,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,2020,01001,L'Abergement-Clémenciat,1400.0,01,Ain,84,Auvergne-Rhône-Alpes,779,48.7,16,46.153,4.926,8405.0
1,2020,01002,L'Abergement-de-Varey,1640.0,01,Ain,84,Auvergne-Rhône-Alpes,256,27.1,9,46.009,5.428,8405.0
2,2020,01004,Ambérieu-en-Bugey,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,14134,570.5,24,45.961,5.373,8405.0
3,2020,01005,Ambérieux-en-Dombes,1330.0,01,Ain,84,Auvergne-Rhône-Alpes,1751,106.1,16,45.996,4.912,8434.0
4,2020,01006,Ambléon,1300.0,01,Ain,84,Auvergne-Rhône-Alpes,112,18.9,6,45.750,5.594,8404.0
5,2020,01007,Ambronay,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,2800,81.3,34,46.006,5.358,8405.0
6,2020,01008,Ambutrix,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,762,144.1,5,45.937,5.333,8405.0
7,2020,01009,Andert-et-Condon,1300.0,01,Ain,84,Auvergne-Rhône-Alpes,326,47.6,7,45.787,5.658,8404.0
8,2020,01010,Anglefort,1350.0,01,Ain,84,Auvergne-Rhône-Alpes,1105,38.1,29,45.909,5.795,8416.0
9,2020,01011,Apremont,1100.0,01,Ain,84,Auvergne-Rhône-Alpes,368,25.8,15,46.206,5.658,8425.0

#### Merge par code_postal

In [598]:
df_vf = pd.read_csv(r'raw\csv_agg_all.csv', sep=';')
df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_16100\3494460096.py:2: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi, 5: grille_densite, 6: code_unite_urbaine, 7: nom_unite_urbaine, 8: type_commune_unite_urbaine, 9: statut_commune_unite_urbaine, 10: grille_densite_texte, 11: niveau_equipements_services_texte) have mixed types. Specify dtype option on import or set low_memory=False.
  df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

In [599]:
print(df_vf['annee'].value_counts().sort_index())

annee
2020    31891
2021    33225
2022    33356
2023    33160
2024    33113
2025    30545
Name: count, dtype: int64

In [600]:
cols_commune = [
    'annee','code_insee', 'nom_standard', 'code_postal',
    'dep_code', 'dep_nom', 'reg_code', 'reg_nom',
    'population', 'densite', 'superficie_km2',
    'latitude_centre', 'longitude_centre','zone_emploi'
]
df_comm = df_comm[cols_commune]

In [601]:
df_comm.columns

Index(['annee', 'code_insee', 'nom_standard', 'code_postal', 'dep_code',
       'dep_nom', 'reg_code', 'reg_nom', 'population', 'densite',
       'superficie_km2', 'latitude_centre', 'longitude_centre', 'zone_emploi'],
      dtype='str')

In [602]:
df_vf.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes'], dtype='str')

In [603]:
df_vf['code_commune'] = df_vf['code_commune'].astype(str).str.zfill(5)
df_comm['code_insee'] = df_comm['code_insee'].astype(str).str.zfill(5)

df_merged = df_vf.merge(df_comm,
                              left_on=['code_commune', 'annee'],
                              right_on=['code_insee', 'annee'],
                              how='left')

In [604]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,01001,2020,1508.351938,132.857143,15,01001,L'Abergement-Clémenciat,1400.0,01,Ain,84.0,Auvergne-Rhône-Alpes,779.0,48.7,16.0,46.153,4.926,8405.0
1,01002,2020,2022.908835,47.000000,10,01002,L'Abergement-de-Varey,1640.0,01,Ain,84.0,Auvergne-Rhône-Alpes,256.0,27.1,9.0,46.009,5.428,8405.0
2,01004,2020,2530.613622,91.926136,433,01004,Ambérieu-en-Bugey,1500.0,01,Ain,84.0,Auvergne-Rhône-Alpes,14134.0,570.5,24.0,45.961,5.373,8405.0
3,01005,2020,3277.989223,105.478261,57,01005,Ambérieux-en-Dombes,1330.0,01,Ain,84.0,Auvergne-Rhône-Alpes,1751.0,106.1,16.0,45.996,4.912,8434.0
4,01006,2020,2326.979167,110.000000,12,01006,Ambléon,1300.0,01,Ain,84.0,Auvergne-Rhône-Alpes,112.0,18.9,6.0,45.750,5.594,8404.0

In [605]:
df_taxe_fonciere = pd.read_csv(csv_taxe_fonciere) 
df_taxe_fonciere.head(10)

df_taxe_2025 = df_taxe_fonciere[df_taxe_fonciere['annee_cible'] == 2024].copy()
df_taxe_2025['annee_cible'] = 2025

df_taxe_fonciere = pd.concat([df_taxe_fonciere, df_taxe_2025], ignore_index=True)

df_taxe_2020 = df_taxe_fonciere[df_taxe_fonciere['annee_cible'] == 2021].copy()
df_taxe_2020['annee_cible'] = 2020

df_taxe_fonciere = pd.concat([df_taxe_fonciere, df_taxe_2020], ignore_index=True)

df_merged['dep_code'] = df_merged['dep_code'].astype(str).str.zfill(2)
df_taxe_fonciere['dept'] = df_taxe_fonciere['dept'].astype(str).str.zfill(2)

df_merged['annee'] = df_merged['annee'].astype(int)
df_taxe_fonciere['annee_cible'] = df_taxe_fonciere['annee_cible'].astype(int)

print(df_taxe_fonciere['annee_cible'].value_counts().sort_index())

annee_cible
2020    101
2021    101
2022    101
2023    101
2024    101
2025    101
Name: count, dtype: int64

In [606]:
df_merged = df_merged.merge(
    df_taxe_fonciere[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']],
    left_on=['dep_code', 'annee'],
    right_on=['dept', 'annee_cible'],
    how='left'
)

In [607]:
df_merged[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']].info()

<class 'pandas.DataFrame'>
RangeIndex: 195290 entries, 0 to 195289
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   dept              195215 non-null  str
 1   annee_cible       195215 non-null  float64
 2   taux_global_tfb   195215 non-null  float64
 3   taux_global_tfnb  195215 non-null  float64
 4   taux_plein_teom   183235 non-null  float64
 5   taux_global_th    195215 non-null  float64
dtypes: float64(5), str(1)
memory usage: 8.9 MB

In [608]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,...,superficie_km2,latitude_centre,longitude_centre,zone_emploi,dept,annee_cible,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th
0,01001,2020,1508.351938,132.857143,15,01001,L'Abergement-Clémenciat,1400.0,01,Ain,...,16.0,46.153,4.926,8405.0,01,2020.0,38.81,118.52,9.95,28.64
1,01002,2020,2022.908835,47.000000,10,01002,L'Abergement-de-Varey,1640.0,01,Ain,...,9.0,46.009,5.428,8405.0,01,2020.0,38.81,118.52,9.95,28.64
2,01004,2020,2530.613622,91.926136,433,01004,Ambérieu-en-Bugey,1500.0,01,Ain,...,24.0,45.961,5.373,8405.0,01,2020.0,38.81,118.52,9.95,28.64
3,01005,2020,3277.989223,105.478261,57,01005,Ambérieux-en-Dombes,1330.0,01,Ain,...,16.0,45.996,4.912,8434.0,01,2020.0,38.81,118.52,9.95,28.64
4,01006,2020,2326.979167,110.000000,12,01006,Ambléon,1300.0,01,Ain,...,6.0,45.750,5.594,8404.0,01,2020.0,38.81,118.52,9.95,28.64

In [609]:
vf_annee = df_merged.groupby(['annee', 'code_postal'], dropna=False).agg(
    prix_m2=('prix_m2', 'mean'),
    dep_code=('dep_code', 'first'),
    dep_nom=('dep_nom', 'first'),
    reg_code=('reg_code', 'first'),
    reg_nom=('reg_nom', 'first'),
    population=('population', 'sum'),
    superficie_km2=('superficie_km2', 'sum'),  
    zone_emploi=('zone_emploi', 'first'),
    taux_global_tfb=('taux_global_tfb', 'mean'),
    taux_global_tfnb=('taux_global_tfnb', 'mean'),
    taux_plein_teom=('taux_plein_teom', 'mean'),
    taux_global_th=('taux_global_th', 'mean'),
    nb_ventes=('nb_ventes', 'sum')
).reset_index()


vf_annee = vf_annee.sort_values(['code_postal', 'annee'])
vf_annee['variation'] = vf_annee.groupby('code_postal')['prix_m2'].pct_change()
vf_annee = vf_annee[vf_annee['annee'] != 2020].reset_index(drop=True)


"""
def market_trend(x, seuil=0.02):  
    if x > seuil:
        return 'hausse'
    elif x < -seuil:
        return 'baisse'
    else:
        return 'stable'
    
vf_annee['y'] = vf_annee['variation'].apply(market_trend)
"""

"\ndef market_trend(x, seuil=0.02):  \n    if x > seuil:\n        return 'hausse'\n    elif x < -seuil:\n        return 'baisse'\n    else:\n        return 'stable'\n\nvf_annee['y'] = vf_annee['variation'].apply(market_trend)\n"

In [610]:
df_inflation = pd.read_csv(taux_inflation, sep=';', parse_dates=['Date'])
print(df_inflation.columns.tolist())
df_inflation.rename(columns={"Taux d’inflation": "taux_inflation"}, inplace=True)

['Date', 'Taux d’inflation']

In [611]:
df_inflation['annee'] = df_inflation['Date'].dt.year
df_inflation['taux_inflation'] = df_inflation["taux_inflation"] / 100

In [612]:
df_inflation['taux_inflation']

0     0.007
1     0.008
2     0.008
3     0.011
4     0.008
      ...
67    0.004
68    0.004
69    0.008
70    0.016
71    0.017
Name: taux_inflation, Length: 72, dtype: float64

In [613]:
inflation_par_annee = (
    df_inflation
    .sort_values('Date')
    .groupby('annee')['taux_inflation']
    .last()        
    .to_dict()
)

if 2025 not in inflation_par_annee:
    inflation_par_annee[2025] = inflation_par_annee[2024]
    
vf_annee['taux_inflation'] = vf_annee['annee'].map(inflation_par_annee)

def market_trend_dynamic(row):
    x = row['variation']       
    seuil = row['taux_inflation']  

    if pd.isna(x) or pd.isna(seuil):
        return None

    if x > seuil:
        # Le prix augmente AU-DELÀ de l'inflation → hausse réelle
        return 'hausse'
    elif x < - seuil :
        # Le prix baisse en valeur nominale → baisse réelle (peu importe l'inflation)
        return 'baisse'
    else:
        # Le prix augmente mais moins que l'inflation → stable en termes réels
        return 'stable'

vf_annee['y'] = vf_annee.apply(market_trend_dynamic, axis=1)

In [614]:
vf_annee.head(10)

,annee,code_postal,prix_m2,dep_code,dep_nom,reg_code,reg_nom,population,superficie_km2,zone_emploi,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th,nb_ventes,variation,taux_inflation,y
0,2021,1000.0,2958.353712,01,Ain,84.0,Auvergne-Rhône-Alpes,47054.0,37.0,8405.0,38.81,118.52,9.95,28.64,2882,-0.034187,0.034,baisse
1,2022,1000.0,4903.185023,01,Ain,84.0,Auvergne-Rhône-Alpes,47054.0,37.0,8405.0,38.82,118.47,9.95,28.63,3232,0.657403,0.067,hausse
2,2023,1000.0,2856.920423,01,Ain,84.0,Auvergne-Rhône-Alpes,47652.0,37.0,8405.0,38.82,118.53,9.95,28.62,2743,-0.417334,0.041,baisse
3,2024,1000.0,2833.934311,01,Ain,84.0,Auvergne-Rhône-Alpes,47652.0,37.0,8405.0,40.25,121.52,9.95,29.62,2336,-0.008046,0.018,stable
4,2025,1000.0,4154.730477,01,Ain,84.0,Auvergne-Rhône-Alpes,47588.0,37.0,8405.0,40.25,121.52,9.95,29.62,877,0.466064,0.007,hausse
5,2021,1090.0,2618.868701,01,Ain,84.0,Auvergne-Rhône-Alpes,9048.0,41.0,8434.0,38.81,118.52,9.95,28.64,600,-0.058184,0.034,baisse
6,2022,1090.0,3208.893962,01,Ain,84.0,Auvergne-Rhône-Alpes,9048.0,41.0,8434.0,38.82,118.47,9.95,28.63,539,0.225298,0.067,hausse
7,2023,1090.0,3241.507502,01,Ain,84.0,Auvergne-Rhône-Alpes,9062.0,41.0,8434.0,38.82,118.53,9.95,28.62,453,0.010163,0.041,stable
8,2024,1090.0,3059.560459,01,Ain,84.0,Auvergne-Rhône-Alpes,9062.0,41.0,8434.0,40.25,121.52,9.95,29.62,320,-0.056130,0.018,baisse
9,2025,1090.0,2110.953511,01,Ain,84.0,Auvergne-Rhône-Alpes,8463.0,37.0,8434.0,40.25,121.52,9.95,29.62,136,-0.310047,0.007,baisse

In [615]:
vf_annee.columns

Index(['annee', 'code_postal', 'prix_m2', 'dep_code', 'dep_nom', 'reg_code',
       'reg_nom', 'population', 'superficie_km2', 'zone_emploi',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th', 'nb_ventes', 'variation', 'taux_inflation', 'y'],
      dtype='str')

In [616]:
df_emploi = pd.read_csv(nbr_emploi_par_region, sep=',', skiprows=3, header=0)
df_emploi = df_emploi.rename(columns={'Unnamed: 0': 'reg_nom'})

df_emploi = df_emploi.rename(columns={
    'Emploi total': 'emploi_total',
    'Emploi non salarié': 'emploi_non_salarie',
    'Emploi salarié': 'emploi_salarie',
    'Agriculture': 'part_agriculture',
    'Industrie': 'part_industrie',
    'Construction': 'part_construction',
    'Tertiaire marchand': 'part_tertiaire_marchand',
    'Tertiaire non marchand': 'part_tertiaire_non_marchand'
})

In [617]:
df_emploi.head()

,reg_nom,emploi_total,emploi_non_salarie,emploi_salarie,part_agriculture,part_industrie,Construction,part_tertiaire_marchand,part_tertiaire_non_marchand
0,Auvergne-Rhône-Alpes,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
1,Bourgogne-Franche-Comté,"1,115",128,988,2.0,17.0,5.0,41.0,35.0
2,Bretagne,"1,458",175,"1,282",2.0,14.0,6.0,44.0,33.0
3,Centre-Val de Loire,"1,043",109,933,1.0,16.0,6.0,44.0,33.0
4,Corse,142,22,120,3.0,6.0,10.0,43.0,38.0

In [618]:
print("vf_annee reg_nom:")
print(sorted(vf_annee['reg_nom'].dropna().unique()))

vf_annee reg_nom:
['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val de Loire', 'Corse', 'Grand Est', 'Guadeloupe', 'Guyane', 'Hauts-de-France', 'La Réunion', 'Martinique', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', "Provence-Alpes-Côte d'Azur", 'Île-de-France']

In [619]:
print("\ndf_emploi reg_nom:")
print(sorted(df_emploi['reg_nom'].dropna().unique()))

df_emploi reg_nom:
['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val de Loire', 'Champ\xa0: France hors Mayotte.', 'Corse', 'France hors Mayotte', 'Grand Est', 'Guadeloupe', 'Guyane', 'Hauts-de-France', 'La Réunion', 'Lecture\xa0: fin 2021, 3,6 millions de personnes sont en emploi en Auvergne-Rhône-Alpes, dont 3,2 millions de salariés\xa0; parmi ces derniers, 48\xa0% sont salariés du tertiaire marchand.', 'Martinique', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', "Provence-Alpes-Côte d'Azur", 'Source\xa0: Insee, Estimations d’emploi.', 'Île-de-France']

In [621]:
regions_valides = vf_annee['reg_nom'].dropna().unique()
df_emploi = df_emploi[df_emploi['reg_nom'].isin(regions_valides)].reset_index(drop=True)

print(df_emploi['reg_nom'].unique())
print(df_emploi.shape)

<StringArray>
[      'Auvergne-Rhône-Alpes',    'Bourgogne-Franche-Comté',
                   'Bretagne',        'Centre-Val de Loire',
                      'Corse',                  'Grand Est',
            'Hauts-de-France',              'Île-de-France',
                  'Normandie',         'Nouvelle-Aquitaine',
                  'Occitanie',           'Pays de la Loire',
 'Provence-Alpes-Côte d'Azur',                 'Guadeloupe',
                     'Guyane',                 'La Réunion',
                 'Martinique']
Length: 17, dtype: str
(17, 9)

In [622]:
print(df_emploi.columns.tolist())

['reg_nom', 'emploi_total', 'emploi_non_salarie', 'emploi_salarie', 'part_agriculture', 'part_industrie', 'Construction ', 'part_tertiaire_marchand', 'part_tertiaire_non_marchand']

In [623]:
vf_annee = vf_annee.merge(
    df_emploi,
    on='reg_nom',
    how='left'
)

In [624]:
vf_annee

,annee,code_postal,prix_m2,dep_code,dep_nom,reg_code,reg_nom,population,superficie_km2,zone_emploi,...,taux_inflation,y,emploi_total,emploi_non_salarie,emploi_salarie,part_agriculture,part_industrie,Construction,part_tertiaire_marchand,part_tertiaire_non_marchand
0,2021,1000.0,2958.353712,01,Ain,84.0,Auvergne-Rhône-Alpes,47054.0,37.0,8405.0,...,0.034,baisse,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
1,2022,1000.0,4903.185023,01,Ain,84.0,Auvergne-Rhône-Alpes,47054.0,37.0,8405.0,...,0.067,hausse,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
2,2023,1000.0,2856.920423,01,Ain,84.0,Auvergne-Rhône-Alpes,47652.0,37.0,8405.0,...,0.041,baisse,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
3,2024,1000.0,2833.934311,01,Ain,84.0,Auvergne-Rhône-Alpes,47652.0,37.0,8405.0,...,0.018,stable,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
4,2025,1000.0,4154.730477,01,Ain,84.0,Auvergne-Rhône-Alpes,47588.0,37.0,8405.0,...,0.007,hausse,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28664,2021,NaN,2197.181906,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,0.034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28665,2022,NaN,3946.990445,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,0.067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28666,2023,NaN,4034.351868,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,0.041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28667,2024,NaN,5240.051355,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,0.018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28668,2025,NaN,43940.459580,60,Oise,32.0,Hauts-de-France,0.0,5.0,NaN,...,0.007,NaN,"2,345",208,"2,137",1.0,13.0,6.0,45.0,35.0

In [625]:
print(vf_annee['reg_nom'].isna().sum())
print(vf_annee['y'].isna().sum())
print(vf_annee.shape)

4
75
(28669, 26)

In [626]:
vf_annee.columns

Index(['annee', 'code_postal', 'prix_m2', 'dep_code', 'dep_nom', 'reg_code',
       'reg_nom', 'population', 'superficie_km2', 'zone_emploi',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th', 'nb_ventes', 'variation', 'taux_inflation', 'y',
       'emploi_total', 'emploi_non_salarie', 'emploi_salarie',
       'part_agriculture', 'part_industrie', 'Construction ',
       'part_tertiaire_marchand', 'part_tertiaire_non_marchand'],
      dtype='str')

In [627]:
output_path = os.path.join('raw', f'csv_full_post.csv')
vf_annee.to_csv(output_path, index=False, sep=';', encoding='utf-8')